#!/bin/sh
# Licensed to the Apache Software Foundation (ASF) under one or more
# contributor license agreements.  See the NOTICE file distributed with
# this work for additional information regarding copyright ownership.
# The ASF licenses this file to You under the Apache License, Version 2.0
# (the "License"); you may not use this file except in compliance with
# the License.  You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

set -ex

STITCH_FILES="CHANGES.txt LICENSE.txt NOTICE.txt README.txt"

mkdir build
rm -f $STITCH_FILES

for project in common hdfs mapreduce ; do 
  cd $project
  ant  \
    -Djava5.home=$JAVA5_HOME \
    -Dforrest.home=$FORREST_HOME \
    -Dversion=${HADOOP_VERSION} \
    -Dcompile.native=true \
    -Dhadoop.conf.dir=/etc/hadoop/conf \
    -Dlibhdfs=1 -Dfusedfs=true -Dcompile.c++=true -Djdiff.build.dir=build/docs/jdiff-cloudera \
   api-report bin-package $BUILD_CONTRIB package \
    "$@"
  (cd build/hadoop-*-0.22 ; tar cf - * ) | (cd ../build ; tar xf - )

  for file in $STITCH_FILES ; do
    [ -f $file ] && cat $file >> ../$file
  done
  
  BUILD_CONTRIB="compile-contrib"
  cd ..
done
